import { referenceAgent } from './reference-agents'

/**
 * Visual identity for Marque's six reference agents (27 Sep identity pass;
 * DESIGN-SYSTEM.md section 13). One manifest, one source of truth for tuning.
 *
 * Avatar = the operative, the "who". Hero = the instrument, the "what".
 * First-party only: a third-party agent never resolves here, so it keeps its
 * registry image or the generated emblem (invariant 1, 17). Identity never
 * changes ranking, state colours or any figure.
 *
 * Resolution goes through reference-agents.ts (a `marque:*` id, a slug, or the
 * canonical ERC-8004 row id / mainnet token id), never through a display name.
 * Masters live in brand-assets/agents-brand; the web copies are generated by
 * scripts/prepare-brand-assets.mjs into public/brand/agents/<slug>/.
 */
export type AgentTone = 'steel' | 'lattice' | 'brass' | 'verdigris' | 'opal' | 'garnet'

export interface AgentBrand {
  slug: string
  /** 512 px square, for 72 px and up. */
  avatar: string
  /** 160 px square, for cards and lists. */
  avatarSmall: string
  /** 1800 px, about 3:1 (Sluicegate 2:1), the storefront masthead. */
  hero: string
  /** 900 px, phones. */
  heroSmall: string
  /** object-position that keeps the artifact in frame when the stage crops. */
  heroPosition: string
  tone: AgentTone
}

const MANIFEST: Record<string, { tone: AgentTone; heroPosition: string }> = {
  keel: { tone: 'steel', heroPosition: '68% 52%' },
  lattice: { tone: 'lattice', heroPosition: '68% 50%' },
  bound: { tone: 'brass', heroPosition: '68% 50%' },
  sluicegate: { tone: 'verdigris', heroPosition: '73% 46%' },
  tidemark: { tone: 'opal', heroPosition: '68% 52%' },
  redcell: { tone: 'garnet', heroPosition: '68% 50%' },
}

function build(slug: string): AgentBrand | null {
  const m = MANIFEST[slug]
  if (!m) return null
  const base = `/brand/agents/${slug}`
  return {
    slug,
    avatar: `${base}/avatar.webp`,
    avatarSmall: `${base}/avatar-160.webp`,
    hero: `${base}/hero.webp`,
    heroSmall: `${base}/hero-900.webp`,
    heroPosition: m.heroPosition,
    tone: m.tone,
  }
}

/** The brand for a reference agent, or null for everyone else. */
export function agentBrand(idOrSlug: string | null | undefined): AgentBrand | null {
  const ref = referenceAgent(idOrSlug)
  return ref ? build(ref.slug) : null
}
