/**
 * Snapshot @bnbagent/sdk 0.6.0 into src/generated.ts: canonical addresses, the payment
 * asset catalog and the ABIs the buyer rail needs.
 *
 * Why a snapshot: the browser bundle must not import the SDK (it drags wallet providers
 * and Node dependencies), and app code must never hand-type an address. The snapshot is
 * generated from the pinned SDK, and a unit test re-derives it and fails on any drift.
 *
 *   pnpm --filter @marque/commerce codegen
 */
import { writeFileSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { NETWORKS } from '@bnbagent/sdk'
import { BNB_CHAIN_ADDRESSES, listAssets } from '@bnbagent/sdk/networks'

const here = path.dirname(new URL(import.meta.url).pathname)
const require = createRequire(import.meta.url)
// The package's exports map hides package.json; locate the package from its main entry.
const sdkRoot = path.resolve(path.dirname(require.resolve('@bnbagent/sdk')), '..')
const sdkPkg = JSON.parse(readFileSync(path.join(sdkRoot, 'package.json'), 'utf8')) as { version: string }

// The ABIs are not part of the SDK's public exports; read them from its bundle.
const dist = path.join(sdkRoot, 'dist')
function grabAbi(file: string, name: string): unknown[] {
  const src = readFileSync(path.join(dist, file), 'utf8')
  const i = src.indexOf(`var ${name} = `)
  if (i < 0) throw new Error(`${name} not found in ${file}`)
  const j = src.indexOf('[', i)
  let d = 0
  let k = j
  for (; k < src.length; k++) {
    if (src[k] === '[') d++
    else if (src[k] === ']') { d--; if (!d) break }
  }
  return (0, eval)(`(${src.slice(j, k + 1)})`) as unknown[]
}
function findChunk(name: string): string {
  const fs = require('node:fs') as typeof import('node:fs')
  for (const f of fs.readdirSync(dist)) {
    if (!f.endsWith('.js')) continue
    if (fs.readFileSync(path.join(dist, f), 'utf8').includes(`var ${name} = `)) return f
  }
  throw new Error(`no chunk defines ${name}`)
}

type AbiItem = { type: string; name?: string }
const keep = (abi: unknown[], names: string[]) =>
  (abi as AbiItem[]).filter((x) => x.type === 'error' || (x.name !== undefined && names.includes(x.name)))

const commerceAbi = grabAbi(findChunk('agenticCommerceAbi'), 'agenticCommerceAbi')
const routerAbi = grabAbi(findChunk('evaluatorRouterAbi'), 'evaluatorRouterAbi')
const policyAbi = grabAbi(findChunk('optimisticPolicyAbi'), 'optimisticPolicyAbi')

const COMMERCE_FNS = [
  'createJob', 'createJobWithToken', 'setBudget', 'fund', 'reject', 'claimRefund', 'getJob', 'jobPaymentToken',
  'isPaymentTokenSupported', 'paymentToken', 'jobCounter',
  'JobCreated', 'BudgetSet', 'JobFunded', 'JobSubmitted', 'JobCompleted', 'PaymentReleased', 'JobRejected',
  'JobExpired', 'Refunded', 'JobPaymentTokenBound', 'ProviderSet',
]
const ROUTER_FNS = ['registerJob', 'settle', 'markExpired', 'jobPolicy', 'JobRegistered', 'JobSettled', 'JobFinalised']
const POLICY_FNS = ['dispute', 'disputeWindow', 'submittedAt', 'disputed', 'Disputed', 'VoteCast', 'QuorumReached']

const networks = Object.values(NETWORKS).map((n) => {
  const dep = BNB_CHAIN_ADDRESSES[n.chainId]!
  return {
    key: n.name,
    chainId: n.chainId,
    identityRegistry: n.registryContract,
    commerce: n.commerceContract,
    router: n.routerContract,
    policy: n.policyContract,
    kernelToken: dep.paymentToken,
    assets: listAssets(n.chainId).map((a) => ({ symbol: a.symbol, address: a.address, decimals: a.decimals, isDefault: a.isDefault })),
  }
})

const header = `// GENERATED by packages/commerce/scripts/codegen.mts from @bnbagent/sdk@${sdkPkg.version}. Do not edit.
// src/generated.test.ts re-derives this file from the pinned SDK and fails on drift.
`
const body = `${header}
export const SDK_VERSION = ${JSON.stringify(sdkPkg.version)} as const

export const SDK_NETWORKS = ${JSON.stringify(networks, null, 2)} as const

export const agenticCommerceAbi = ${JSON.stringify(keep(commerceAbi, COMMERCE_FNS))} as const

export const evaluatorRouterAbi = ${JSON.stringify(keep(routerAbi, ROUTER_FNS))} as const

export const optimisticPolicyAbi = ${JSON.stringify(keep(policyAbi, POLICY_FNS))} as const
`
writeFileSync(path.join(here, '..', 'src', 'generated.ts'), body)
console.log(`wrote src/generated.ts from @bnbagent/sdk@${sdkPkg.version}: ${networks.length} networks`)
