/**
 * pnpm supply:audit
 *
 * Per category: hireable, quoteable, preview_only and callable services, with agent,
 * operator, chain, price and quote age, from stored first-party observations only.
 * Writes docs/phase2/SUPPLY.md and docs/phase2/OUTREACH.md. Contacts nobody.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { sql } from 'drizzle-orm'
import { db, closeDb } from '@marque/db'
import { coverage, QUEST_CATEGORIES, type CoverageAgent } from '../src/supply.js'
import { formatAmount } from '../src/config.js'

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../../..')
const rowsOf = (r: unknown) => ((r as { rows?: unknown[] }).rows ?? (r as unknown[])) as Array<Record<string, unknown>>
const short = (a: string | null) => (a ? `${a.slice(0, 6)}...${a.slice(-4)}` : 'unknown')
const chainName = (id: number | null) => (id === 56 ? 'BSC mainnet (56)' : id === 97 ? 'BSC testnet (97)' : 'none')

const FIX: Record<string, string> = {
  provider_mismatch: 'Sign quotes with the wallet registered as this agent in the ERC-8004 registry (getAgentWallet), or call setAgentWallet to register the signing key.',
  unsigned: 'The seller returns quotes without provider_sig. Configure the signing key for the provider wallet so negotiate returns a signed NegotiationResult.',
  malformed: 'negotiate must return a NegotiationResult with request_hash, response_hash, negotiation_hash (32-byte hex) and provider_sig, as the Agent Studio runtime does.',
  unreachable: 'The A2A card URL did not accept a JSON-RPC message/send (see detail). Serve A2A at the card url without auth for negotiate.',
  no_quote: 'The card URL answered, but not with a NegotiationResult. Route {"skill":"negotiate"} data parts to the seller core at the card url.',
  not_a2a: 'The card URL did not return JSON. Serve A2A JSON-RPC at the url named in the agent card.',
  chain_unsupported: 'Quote on BSC mainnet (56) or testnet (97).',
  wrong_contract: 'Bind quotes to the canonical AgenticCommerce contract for the chain (verifying_contract).',
  currency_unsupported: 'Quote in a catalog asset (U, USDT, USDC or USD1 on mainnet).',
  no_price: 'Quote a positive price.',
  expired: 'The quote expired before it arrived; check the seller clock and quote_ttl_seconds.',
  declined: 'The seller declined the probe task; accept a generic price-check task or document the required task schema.',
}

const cov = await coverage()

// Callable supply that exposes no negotiation at all (preview only), per category.
const callable = rowsOf(await db().execute(sql`
  with lp as (select ps.service_id, ps.agent_id, p.liveness, p.executable_endpoint, p.checked_at from probe_schedule ps join probe p on p.id = ps.last_probe_id),
  cat as (select distinct on (agent_id) agent_id, category from agent_category order by agent_id, (category <> 'unclassified') desc, confidence desc)
  select cat.category, count(distinct lp.agent_id)::int as n
  from lp join cat on cat.agent_id = lp.agent_id
  where lp.liveness = 'live' and lp.executable_endpoint is not null and lp.checked_at > now() - interval '24 hours'
  group by 1`))
const callableBy = new Map(callable.map((r) => [String(r['category']), Number(r['n'])]))
const classification = rowsOf(await db().execute(sql`
  with cat as (select distinct on (agent_id) agent_id, category from agent_category order by agent_id, (category <> 'unclassified') desc, confidence desc)
  select coalesce(cat.category, 'none') as category, count(*)::int as n from agent a left join cat on cat.agent_id = a.id where a.chain_id = 56 group by 1 order by 2 desc`))

const price = (a: CoverageAgent) => a.quote?.priceRaw && a.quote.decimals !== null ? `${formatAmount(a.quote.priceRaw, a.quote.decimals)} ${a.quote.token}` : 'n/a'
const age = (a: CoverageAgent) => (a.quote?.ageSeconds != null ? `${Math.round(a.quote.ageSeconds / 60)} min` : 'never')

let md = `# SUPPLY.md\n\nGenerated by \`pnpm supply:audit\` at ${cov.measuredAt}. Every number is a stored first-party observation:\n` +
  `a signed ERC-8183 quote the quote worker asked for, or a live probe. Nothing is estimated.\n\n` +
  `Hireable means: a quote in the last 2 hours, signed by the agent's own ERC-8004 wallet, bound to a supported chain and the canonical\n` +
  `AgenticCommerce contract, in a catalog token, with a positive price (SPEC-COMMERCE 4.1).\n\n## Summary\n\n` +
  `| Category | Hireable | Operators (third-party) | First-party | Quoteable, failing a check | Callable, no negotiation | Cheapest live quote |\n|---|---|---|---|---|---|---|\n`
for (const c of cov.categories) {
  const quoteable = c.agents.filter((a) => a.state === 'quoteable').length
  const cheap = c.cheapest ? `${formatAmount(c.cheapest.priceRaw, c.cheapest.decimals)} ${c.cheapest.token} on ${c.cheapest.chainId}` : 'none'
  md += `| ${c.category}${(QUEST_CATEGORIES as readonly string[]).includes(c.category) ? '' : ' (outside the quest)'} | **${c.hireable}** | ${c.operators} (${c.thirdPartyOperators}) | ${c.firstParty} | ${quoteable} | ${callableBy.get(c.category) ?? 0} | ${cheap} |\n`
}
md += `\n## Per category\n`
for (const c of cov.categories) {
  md += `\n### ${c.category}\n\n| Agent | Token id | Operator | State | Chain | Price | Quote | Quote age | Why not hireable |\n|---|---|---|---|---|---|---|---|---|\n`
  for (const a of c.agents.filter((x) => x.state !== 'unavailable' || x.advertisesCommerce || x.firstParty)) {
    md += `| ${a.name}${a.firstParty ? ' (Marque reference)' : ''} | ${a.tokenId} | ${short(a.owner)} | ${a.state} | ${chainName(a.quote?.chainId ?? null)} | ${price(a)} | ${a.signed === null ? '' : a.signed ? 'signed' : 'unsigned, provider = registered wallet'} | ${age(a)} | ${a.failure ? `${a.failure}: ${(a.failureDetail ?? '').replace(/\|/g, '/').slice(0, 110)}` : ''} |\n`
  }
  if (!c.agents.length) md += `| none | | | | | | | |\n`
}
md += `\n## Hireable but unclassified (not counted in any category)\n\n`
md += cov.unclassifiedHireable.length
  ? cov.unclassifiedHireable.map((a) => `- ${a.name} (token ${a.tokenId}, operator ${short(a.owner)}): ${price(a)} on chain ${a.quote?.chainId}`).join('\n') + '\n'
  : 'None.\n'
md += `\n## Classification coverage (chain 56 identities)\n\n| Category | Identities |\n|---|---|\n` + classification.map((r) => `| ${r['category']} | ${Number(r['n']).toLocaleString('en-US')} |`).join('\n') + '\n'
// Agent names are third-party data; the docs render their em/en dashes as hyphens (lint:copy).
const plain = (t: string) => t.replace(/[\u2013\u2014]/g, '-')
writeFileSync(path.join(root, 'docs/phase2/SUPPLY.md'), plain(md))

let out = `# OUTREACH.md\n\nGenerated by \`pnpm supply:audit\` at ${cov.measuredAt}. For Francis: agents that already run an ERC-8183 seller but fail one\n` +
  `hire check, with the exact fix. Marque contacts nobody; this is a list, not a campaign. Fixing any of these adds a hireable agent\n` +
  `to its category with no work on our side, and the builder page (P2-10) walks an owner through the same checks.\n\n`
const byOwner = new Map<string, Array<CoverageAgent & { category: string }>>()
for (const c of cov.categories) for (const a of c.agents) {
  if (a.state === 'hireable' || a.state === 'settleable' || a.firstParty) continue
  // Only real sellers that fail a fixable check: the card advertises ERC-8183, or the agent
  // answered with a quote that failed verification. Agents that never quoted are not leads.
  const answeredQuote = a.failure !== null && !['unreachable', 'no_quote', 'not_a2a'].includes(a.failure)
  if (!a.advertisesCommerce && !answeredQuote) continue
  const k = (a.owner ?? a.agentId).toLowerCase()
  byOwner.set(k, [...(byOwner.get(k) ?? []), { ...a, category: c.category }])
}
const ranked = [...byOwner.entries()].sort((a, b) => b[1].length - a[1].length)
out += `| Operator (owner) | Agents | Categories | Endpoint host | Missing piece | Fix |\n|---|---|---|---|---|---|\n`
for (const [owner, list] of ranked) {
  const reasons = [...new Set(list.map((a) => a.failure ?? 'no quote yet'))]
  const hosts = [...new Set(list.map((a) => { try { return new URL(a.endpoint).host } catch { return a.endpoint } }))]
  out += `| \`${owner}\` | ${list.map((a) => `${a.name} (${a.tokenId})`).join(', ')} | ${[...new Set(list.map((a) => a.category))].join(', ')} | ${hosts.join(', ')} | ${reasons.join(', ')} | ${reasons.map((r) => FIX[r] ?? 'See SUPPLY.md').join(' ')} |\n`
}
writeFileSync(path.join(root, 'docs/phase2/OUTREACH.md'), plain(out))

for (const c of cov.categories) console.log(`${c.category.padEnd(14)} hireable ${c.hireable}  operators ${c.operators} (third-party ${c.thirdPartyOperators})  first-party ${c.firstParty}  quoteable ${c.agents.filter((a) => a.state === 'quoteable').length}`)
console.log(`outreach operators: ${ranked.length}`)
await closeDb()
