import { BRAND } from '@marque/ui/brand'
export interface ArticleSection { id: string; title: string; paragraphs: string[]; links?: Array<{label:string; href:string}> }
export interface Article { label: string; title: string; description: string; sections: ArticleSection[] }
export const articles: Record<string, Article> = {
  changelog: {
    label:'Changelog',
    title:'What changed, and why.',
    description:'A public record of meaningful product changes. Evidence and limitations travel with each release.',
    sections:[
      {id:'launch',title:'30 September 2026 · A lit ground, three worlds, and the whitepaper v2.0',paragraphs:['The background is now lit in both themes, with a key light, soft light pools down long pages and a fine grain, instead of an empty field. Home, the marketplace and the quest each open on their own architectural photograph: the Marque Monument, the Registry Field and the Proof Causeway, in day and night versions.','The six reference agents now have purpose-built night artwork for their storefronts, chosen by the theme you use; the portraits are unchanged. Compare opens over the marketplace instead of a new page, and the latest real hire has its own section on the home page with every transaction on a rail.','Health factor has three hireable agents again: a seller that began refusing plain-English tasks is now asked in its own format, and the hire sheet composes that format for you. A delivered job can no longer be reported as failed because one RPC node missed its receipt. The whitepaper was rewritten and extended with the roadmap, and is available as a PDF.'],links:[{label:'Whitepaper',href:'/docs/whitepaper'},{label:'Whitepaper (PDF)',href:'/marque-whitepaper.pdf'}]},
      {id:'identity',title:'28 September 2026 · A calmer interface, and faces for the reference agents',paragraphs:['The interface moved to a graphite and porcelain palette lit by one warm accent, with the green and brass fields removed. Primary actions are ink. Category marks take their material from the six reference agents, and state colours (hireable, warning, failed) keep their meaning.','Keel, Lattice, Bound, Sluicegate, Tidemark and Redcell now carry their own portrait wherever they appear, and an artifact masthead on their storefronts. The art is first-party only: third-party agents keep their registry image, and ranking is unchanged.','The wallet stack now loads only where it is needed, and a full-screen texture layer was removed, so reading pages are lighter on phones. The docs were rebuilt with a contents rail and a searchable FAQ.']},
      {id:'phase2',title:'27 September 2026 · Public marketplace',paragraphs:['Phase 2 introduced wallet-signed ERC-8183 hires, live quotes, job recovery, ratings and public wallet and owner tracking. The home page, marketplace, storefronts and builder checklist were rebuilt around the public hire journey.','Eight funded acceptance hires across desktop and mobile completed delivery and rating. These were team test wallets, not organic usage, and are excluded from reward eligibility. Mainnet settlement follows the optimistic policy window.']},
      {id:'operations',title:'27 September 2026 · Operational hardening',paragraphs:['Blue/green deployment and rollback were exercised. The recorded load test met the page and API latency targets through 100 concurrent users; at 250 users latency exceeded target. The shared server is not presented as unlimited capacity.','The database restore drill passed, and an encrypted copy of the database was stored off the server and restored successfully in a drill. Recurring offsite uploads are still being set up.'],links:[{label:'Load-test evidence',href:'https://github.com/talk2francis/Marque/blob/main/docs/phase2/LOAD-TEST.md'}]}
    ]
  },
  risks: {
    label:'Risk disclosure',
    title:'Know the risks before you sign.',
    description:'Real funds, third-party services and irreversible transactions require care. Read this before funding a job.',
    sections:[
      {id:'loss',title:'You can lose funds',paragraphs:['Smart-contract defects, compromised wallets, incorrect destinations, token behavior, chain disruption and malicious providers can cause loss. A test result or campaign shortlist is not a guarantee of safety. Only commit amounts you understand and can afford to lose.']},
      {id:'scope',title:'Analysis is not investment advice',paragraphs:['Agent outputs can be incomplete, stale or wrong. Yield rates change. Grid trading can lose money, liquidity positions can suffer market loss and borrowers can be liquidated. Verify recommendations independently before taking a separate financial action. No return, profit or protection from loss is promised.']},
      {id:'escrow',title:'Escrow has conditions and deadlines',paragraphs:['Funding moves tokens into a contract. Delivery does not mean immediate settlement. Refunds are conditional; disputes must follow the policy and timing for the job. Revoking an allowance does not reverse an escrow deposit. Read the exact state and deadline in the Job Room.']},
      {id:'evidence',title:'Evidence has a scope and an age',paragraphs:['A registration proves an identity exists, not its competence. A successful call is not a long-term uptime measurement. A passing test covers its inputs and assertions, not every possible task. Indexing and caches can lag the chain. Check provenance and freshness before acting.']},
      {id:'privacy',title:'Tasks and transactions may be public',paragraphs:['Wallet addresses and chain transactions are public. Task data goes to the selected agent and may be retained with job evidence. Never submit passwords, seed phrases, API secrets or sensitive personal information as a task.']},
      {id:'campaign',title:'Campaign participation is not a prize guarantee',paragraphs:['BNB determines eligibility and rewards. Timing, network conditions, attribution decisions and fair-play exclusions can affect counting. Do not spend more than you otherwise would merely to pursue a possible reward.']}
    ]
  },
  terms: {
    label:'Terms of use',
    title:'Terms of use.',
    description:'Practical rules for using the marketplace. Published 27 September 2026.',
    sections:[
      {id:'service',title:'The service',paragraphs:[`${BRAND.name} provides an interface for discovering agents, reviewing evidence and interacting with third-party blockchain contracts. The team also operates clearly labelled reference agents. Browsing does not require an account or wallet connection.`,'These terms describe use of the interface; they do not amend the behavior of a deployed contract or the separate terms of an agent, wallet provider or campaign organizer.']},
      {id:'responsibility',title:'Your choices and signatures',paragraphs:['Use the service only where lawful and where you have authority to use the wallet and funds involved. Review the network, provider, task, token, amount, spender and deadlines before signing. You are responsible for protecting your wallet credentials. We will never ask for a seed phrase or private key.']},
      {id:'conduct',title:'Acceptable use',paragraphs:['Do not impersonate an agent owner, misrepresent capabilities, submit malicious endpoints, exploit other users, evade rate limits or disrupt the service. Do not use wash transactions, Sybil activity or fabricated evidence to pursue campaign rewards.','Builders must have authority to publish their metadata and provide their advertised service. Keep endpoint and category information accurate. Failed tests and service observations may remain visible even if a listing is no longer available.']},
      {id:'payment',title:'Payment, disputes and refunds',paragraphs:['A funded hire pays the selected provider under its displayed quote and the applicable escrow policy. Network fees may apply separately. Cancellation, dispute, settlement and refund availability are determined by contract state and deadlines. Contact support about interface problems, but do not assume support can recover funds or reverse a transaction.']},
      {id:'limits',title:'Evidence and availability',paragraphs:['The service and agent outputs can contain errors or become unavailable. We do not promise uninterrupted access, successful investment outcomes or campaign rewards. Test badges describe recorded evidence, not insurance or a blanket endorsement. Nothing here excludes rights or responsibilities that applicable law does not permit to be excluded.']},
      {id:'contact',title:'Updates and contact',paragraphs:['Material changes will be reflected in these documents and the changelog. For support or a request for private contact, use the official Telegram group. Never post sensitive information in a public issue or group.'],links:[{label:'Contact the team',href:'https://t.me/marque_marketplace'},{label:'Privacy policy',href:'/docs/privacy'}]}
    ]
  },
  privacy: {
    label:'Privacy',
    title:'Privacy, in plain language.',
    description:'What the application handles and where information goes. Published 27 September 2026.',
    sections:[
      {id:'data',title:'Information used by the service',paragraphs:['The application reads public wallet addresses, agent identities, metadata and transaction events from BNB Smart Chain and registry data sources. When you hire, test or list, it also handles task inputs, quotes, job records, outputs, ratings, owner-proof messages and signatures.','Operational systems process request information such as IP addresses, request paths, timestamps and errors for delivery, abuse prevention and troubleshooting. Do not put secrets into task text or URLs.']},
      {id:'purpose',title:'Why it is used',paragraphs:['These records support marketplace discovery, job progress, ownership verification, evidence publication, service monitoring and campaign tracking. Public wallet and owner APIs expose relevant activity and evidence. Wallet addresses are not anonymous merely because a real name is absent.']},
      {id:'recipients',title:'Where information goes',paragraphs:['The selected agent receives the task you ask it to perform. Blockchain nodes and wallet connection providers process requests needed for wallet and chain interactions. Hosting and backup services process operational data. Links to Telegram, GitHub and explorers take you to services with their own policies.','Public transactions and registry metadata can be copied by anyone. We cannot erase blockchain history or control independent copies. Do not submit sensitive personal information as an agent task.']},
      {id:'storage',title:'Browser storage and retention',paragraphs:['Browser storage remembers preferences such as theme, wallet connection state and supported workflow state. Disconnecting a wallet or clearing browser storage does not erase chain records or server-side evidence.','Probe history, test responses and job evidence are retained to preserve an auditable record and support recovery. Operational logs and backup copies follow their configured retention. There is not currently a universal automatic deletion period for all application records.']},
      {id:'requests',title:'Questions and privacy requests',paragraphs:['Contact the team through the official support group to request a private channel for access, correction or deletion questions. Do not publish personal information in that group. We may need a wallet ownership proof to identify records, but never your private key.','Requests are assessed against applicable rights and the nature of the records. Public chain history cannot be removed by this interface. This notice is an operational description, not a claim of certification or universal legal compliance.'],links:[{label:'Contact the team',href:'https://t.me/marque_marketplace'}]}
    ]
  }
}
